# Generated by Django 5.0.6 on 2024-07-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id_contact', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_contact', models.CharField(max_length=200)),
                ('lastnames_contact', models.CharField(max_length=200)),
                ('email_contact', models.EmailField(max_length=200)),
                ('comment_contact', models.TextField(max_length=2000)),
                ('timestamp_contact', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
