# Generated by Django 5.0.6 on 2024-07-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email_contact',
            field=models.EmailField(max_length=254),
        ),
    ]
