# Generated by Django 5.0.6 on 2024-07-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmodel_email_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='ip_contact',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
