# Generated by Django 5.0.6 on 2024-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmodel_ip_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='timestamp_contact',
            field=models.DateTimeField(),
        ),
    ]
